# -*- coding: utf-8 -*-
"""IRIS_flower_classification

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19maAzM46YaOZc7_GrFT37MYg45APnhr6
"""

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt
import seaborn as sns

df=sns.load_dataset('iris')
df.head()

df['species'],categories=pd.factorize(df['species'])
df.head()

df.describe

df.isna().sum()

from mpl_toolkits.mplot3d import Axes3D
fig=plt.figure()
ax=fig.add_subplot(111,projection='3d')
ax.scatter(df.petal_length,df.petal_width,df.species)
ax.set_xlabel('petal_length')
ax.set_ylabel('petal_width')
ax.set_zlabel('species')
plt.title('3D scatter plot example')
plt.show()

from mpl_toolkits.mplot3d import Axes3D
fig=plt.figure()
ax=fig.add_subplot(111,projection='3d')
ax.scatter(df.sepal_length,df.sepal_width,df.species)
ax.set_xlabel('sepal_length')
ax.set_ylabel('sepal_width')
ax.set_zlabel('species')
plt.title('3D scatter plot example')
plt.show()

from cycler import U
sns.scatterplot(data=df,x='petal_length',y='petal_width',hue='species')

from cycler import U
sns.scatterplot(data=df,x='sepal_length',y='sepal_width',hue='species')

k_mg=range(1,10)
ssc=[]
for k in k_mg:
  km=KMeans(n_clusters=k)
  km.fit(df[['petal_length','petal_width']])
  ssc.append(km.inertia_)

ssc

plt.xlabel('K')
plt.ylabel('Sum of squared error')
plt.plot(k_mg,ssc)

km=KMeans(n_clusters=3,random_state=0)
y_predicted=km.fit_predict(df[['petal_length','petal_width']])
y_predicted

df['cluster']=y_predicted
df.head(150)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(df['species'],df.cluster)
cm

true_labels=df.species
predicted_labels=df.cluster
cm=confusion_matrix(true_labels,predicted_labels)

# Get unique class labels for the axes from the true_labels
unique_class_labels = np.unique(true_labels)

plt.imshow(cm,interpolation='nearest',cmap=plt.cm.Blues)
plt.title('confusion matrix')
plt.colorbar()

# Set tick marks and labels based on the unique class labels
tick_marks=np.arange(len(unique_class_labels))
plt.xticks(tick_marks,unique_class_labels)
plt.yticks(tick_marks,unique_class_labels)


# Iterate over the dimensions of the confusion matrix (cm.shape[0] is 3)
for i in range(cm.shape[0]):
  for j in range(cm.shape[1]):
    plt.text(j,i,str(cm[i][j]),ha='center',va='center',color='white')

plt.xlabel('predicted label')
plt.ylabel('true label')
plt.show()